# Generated by Django 3.0.5 on 2020-05-04 13:14

from django.db import migrations, models
import django.db.models.deletion
import imageboard.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=80)),
                ('session_key', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=300)),
                ('comment', models.TextField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to=imageboard.helpers.random_file_name)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'threads',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('name', models.CharField(default='Anonymous', max_length=80)),
                ('comment', models.TextField(max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageboard.Thread')),
            ],
            options={
                'verbose_name_plural': 'replies',
                'ordering': ['-date_created'],
            },
        ),
    ]
